
version: 2

models:
    - name: dim_customers
      description: "Create customers dimension for jaffle shop"
      materialize: "table"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
